// Package orderdemo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package orderdemo

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	OperationalReadTokenScopes operationalReadTokenContextKey = "OperationalReadToken.Scopes"
	RemediationTokenScopes     remediationTokenContextKey     = "RemediationToken.Scopes"
)

// Defines values for ErrorCode.
const (
	IdempotencyConflict      ErrorCode = "idempotency_conflict"
	InternalError            ErrorCode = "internal_error"
	InvalidArgument          ErrorCode = "invalid_argument"
	OperationNotFound        ErrorCode = "operation_not_found"
	QueueFull                ErrorCode = "queue_full"
	ResourceNotFound         ErrorCode = "resource_not_found"
	TargetPreconditionFailed ErrorCode = "target_precondition_failed"
	Unauthenticated          ErrorCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case IdempotencyConflict:
		return true
	case InternalError:
		return true
	case InvalidArgument:
		return true
	case OperationNotFound:
		return true
	case QueueFull:
		return true
	case ResourceNotFound:
		return true
	case TargetPreconditionFailed:
		return true
	case Unauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for OrderFailureReason.
const (
	DependencyUnavailable OrderFailureReason = "dependency_unavailable"
	RetryExhausted        OrderFailureReason = "retry_exhausted"
)

// Valid indicates whether the value is a known member of the OrderFailureReason enum.
func (e OrderFailureReason) Valid() bool {
	switch e {
	case DependencyUnavailable:
		return true
	case RetryExhausted:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCompleted  OrderStatus = "completed"
	OrderStatusFailed     OrderStatus = "failed"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusQueued     OrderStatus = "queued"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCompleted:
		return true
	case OrderStatusFailed:
		return true
	case OrderStatusProcessing:
		return true
	case OrderStatusQueued:
		return true
	default:
		return false
	}
}

// Defines values for ProbeResultResult.
const (
	ProbeResultResultCompleted ProbeResultResult = "completed"
	ProbeResultResultFailed    ProbeResultResult = "failed"
	ProbeResultResultTimedOut  ProbeResultResult = "timed_out"
)

// Valid indicates whether the value is a known member of the ProbeResultResult enum.
func (e ProbeResultResult) Valid() bool {
	switch e {
	case ProbeResultResultCompleted:
		return true
	case ProbeResultResultFailed:
		return true
	case ProbeResultResultTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeSnapshotSupervisorStatus.
const (
	Degraded RuntimeSnapshotSupervisorStatus = "degraded"
	Running  RuntimeSnapshotSupervisorStatus = "running"
)

// Valid indicates whether the value is a known member of the RuntimeSnapshotSupervisorStatus enum.
func (e RuntimeSnapshotSupervisorStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	Quantity int    `json:"quantity"`
	Sku      string `json:"sku"`
}

// Error defines model for Error.
type Error struct {
	Code      ErrorCode `json:"code"`
	Message   string    `json:"message"`
	Retryable bool      `json:"retryable"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// OperationReceipt defines model for OperationReceipt.
type OperationReceipt struct {
	AfterConcurrency  interface{} `json:"afterConcurrency"`
	AfterVersion      int         `json:"afterVersion"`
	ApprovalId        string      `json:"approvalId"`
	BeforeConcurrency interface{} `json:"beforeConcurrency"`
	BeforeVersion     int         `json:"beforeVersion"`
	ExecutedAt        time.Time   `json:"executedAt"`
	InstanceEpoch     string      `json:"instanceEpoch"`
	IntentDigest      string      `json:"intentDigest"`
	OperationId       string      `json:"operationId"`
}

// Order defines model for Order.
type Order struct {
	CreatedAt     time.Time           `json:"createdAt"`
	FailureReason *OrderFailureReason `json:"failureReason"`
	Id            string              `json:"id"`
	Status        OrderStatus         `json:"status"`
	UpdatedAt     time.Time           `json:"updatedAt"`
}

// OrderFailureReason defines model for Order.FailureReason.
type OrderFailureReason string

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// ProbeResult defines model for ProbeResult.
type ProbeResult struct {
	CompletedAt *time.Time        `json:"completedAt"`
	DurationMs  int               `json:"durationMs"`
	OrderId     string            `json:"orderId"`
	ProbeId     string            `json:"probeId"`
	Result      ProbeResultResult `json:"result"`
}

// ProbeResultResult defines model for ProbeResult.Result.
type ProbeResultResult string

// QueueSnapshot defines model for QueueSnapshot.
type QueueSnapshot struct {
	Capacity         interface{} `json:"capacity"`
	Depth            int         `json:"depth"`
	ObservedAt       time.Time   `json:"observedAt"`
	OldestAgeSeconds float32     `json:"oldestAgeSeconds"`
}

// RuntimeSnapshot defines model for RuntimeSnapshot.
type RuntimeSnapshot struct {
	InstanceEpoch    string                          `json:"instanceEpoch"`
	ServiceRef       interface{}                     `json:"serviceRef"`
	StartedAt        time.Time                       `json:"startedAt"`
	SupervisorStatus RuntimeSnapshotSupervisorStatus `json:"supervisorStatus"`
}

// RuntimeSnapshotSupervisorStatus defines model for RuntimeSnapshot.SupervisorStatus.
type RuntimeSnapshotSupervisorStatus string

// UpdateWorkerConfigRequest defines model for UpdateWorkerConfigRequest.
type UpdateWorkerConfigRequest struct {
	ApprovalId          string      `json:"approvalId"`
	ExpectedConcurrency interface{} `json:"expectedConcurrency"`
	ExpectedVersion     int         `json:"expectedVersion"`
	InstanceEpoch       string      `json:"instanceEpoch"`
	IntentDigest        string      `json:"intentDigest"`
	NewConcurrency      interface{} `json:"newConcurrency"`
	OperationId         string      `json:"operationId"`
}

// WorkerConfig defines model for WorkerConfig.
type WorkerConfig struct {
	ActiveWorkers         int         `json:"activeWorkers"`
	ConfiguredConcurrency int         `json:"configuredConcurrency"`
	EffectiveConcurrency  int         `json:"effectiveConcurrency"`
	InflightOrders        int         `json:"inflightOrders"`
	InstanceEpoch         string      `json:"instanceEpoch"`
	ObservedAt            time.Time   `json:"observedAt"`
	ServiceRef            interface{} `json:"serviceRef"`
	Version               int         `json:"version"`
}

// WorkerPolicy defines model for WorkerPolicy.
type WorkerPolicy struct {
	Digest              string      `json:"digest"`
	ExpectedConcurrency interface{} `json:"expectedConcurrency"`
	MaxConcurrency      interface{} `json:"maxConcurrency"`
	MinConcurrency      interface{} `json:"minConcurrency"`
	ServiceRef          interface{} `json:"serviceRef"`
	Version             interface{} `json:"version"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OperationId defines model for OperationId.
type OperationId = string

// OrderId defines model for OrderId.
type OrderId = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// operationalReadTokenContextKey is the context key for OperationalReadToken security scheme
type operationalReadTokenContextKey string

// remediationTokenContextKey is the context key for RemediationToken security scheme
type remediationTokenContextKey string

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListRecentOrdersParams defines parameters for ListRecentOrders.
type ListRecentOrdersParams struct {
	Status *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int         `form:"limit,omitempty" json:"limit,omitempty"`
}

// RunOrderProcessingProbeJSONBody defines parameters for RunOrderProcessingProbe.
type RunOrderProcessingProbeJSONBody struct {
	ProbeId string `json:"probeId"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// UpdateWorkerConfigJSONRequestBody defines body for UpdateWorkerConfig for application/json ContentType.
type UpdateWorkerConfigJSONRequestBody = UpdateWorkerConfigRequest

// RunOrderProcessingProbeJSONRequestBody defines body for RunOrderProcessingProbe for application/json ContentType.
type RunOrderProcessingProbeJSONRequestBody RunOrderProcessingProbeJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateOrderWithBody request with any body
	CreateOrderWithBody(ctx context.Context, params *CreateOrderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOrder(ctx context.Context, params *CreateOrderParams, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrder request
	GetOrder(ctx context.Context, orderId OrderId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Healthz request
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkerConfig request
	GetWorkerConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateWorkerConfigWithBody request with any body
	UpdateWorkerConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateWorkerConfig(ctx context.Context, body UpdateWorkerConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOperation request
	GetOperation(ctx context.Context, operationId OperationId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListRecentOrders request
	ListRecentOrders(ctx context.Context, params *ListRecentOrdersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkerPolicy request
	GetWorkerPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunOrderProcessingProbeWithBody request with any body
	RunOrderProcessingProbeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RunOrderProcessingProbe(ctx context.Context, body RunOrderProcessingProbeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQueue request
	GetQueue(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRuntime request
	GetRuntime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Readyz request
	Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateOrderWithBody(ctx context.Context, params *CreateOrderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrder(ctx context.Context, params *CreateOrderParams, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrderRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrder(ctx context.Context, orderId OrderId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrderRequest(c.Server, orderId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkerConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkerConfigRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateWorkerConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateWorkerConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateWorkerConfig(ctx context.Context, body UpdateWorkerConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateWorkerConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOperation(ctx context.Context, operationId OperationId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOperationRequest(c.Server, operationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListRecentOrders(ctx context.Context, params *ListRecentOrdersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRecentOrdersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkerPolicy(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkerPolicyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RunOrderProcessingProbeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunOrderProcessingProbeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RunOrderProcessingProbe(ctx context.Context, body RunOrderProcessingProbeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunOrderProcessingProbeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQueue(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueueRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRuntime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRuntimeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateOrderRequest calls the generic CreateOrder builder with application/json body
func NewCreateOrderRequest(server string, params *CreateOrderParams, body CreateOrderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrderRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateOrderRequestWithBody generates requests for CreateOrder with any type of body
func NewCreateOrderRequestWithBody(server string, params *CreateOrderParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/orders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetOrderRequest generates requests for GetOrder
func NewGetOrderRequest(server string, orderId OrderId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orderId", orderId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/orders/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthzRequest generates requests for Healthz
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkerConfigRequest generates requests for GetWorkerConfig
func NewGetWorkerConfigRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/config/worker")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateWorkerConfigRequest calls the generic UpdateWorkerConfig builder with application/json body
func NewUpdateWorkerConfigRequest(server string, body UpdateWorkerConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateWorkerConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateWorkerConfigRequestWithBody generates requests for UpdateWorkerConfig with any type of body
func NewUpdateWorkerConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/config/worker")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOperationRequest generates requests for GetOperation
func NewGetOperationRequest(server string, operationId OperationId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "operationId", operationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/operations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListRecentOrdersRequest generates requests for ListRecentOrders
func NewListRecentOrdersRequest(server string, params *ListRecentOrdersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/orders/recent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkerPolicyRequest generates requests for GetWorkerPolicy
func NewGetWorkerPolicyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/policies/worker")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRunOrderProcessingProbeRequest calls the generic RunOrderProcessingProbe builder with application/json body
func NewRunOrderProcessingProbeRequest(server string, body RunOrderProcessingProbeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRunOrderProcessingProbeRequestWithBody(server, "application/json", bodyReader)
}

// NewRunOrderProcessingProbeRequestWithBody generates requests for RunOrderProcessingProbe with any type of body
func NewRunOrderProcessingProbeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/probes/order-processing")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetQueueRequest generates requests for GetQueue
func NewGetQueueRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/queue")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRuntimeRequest generates requests for GetRuntime
func NewGetRuntimeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ops/v1/runtime")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReadyzRequest generates requests for Readyz
func NewReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateOrderWithBodyWithResponse request with any body
	CreateOrderWithBodyWithResponse(ctx context.Context, params *CreateOrderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error)

	CreateOrderWithResponse(ctx context.Context, params *CreateOrderParams, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error)

	// GetOrderWithResponse request
	GetOrderWithResponse(ctx context.Context, orderId OrderId, reqEditors ...RequestEditorFn) (*GetOrderResponse, error)

	// HealthzWithResponse request
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// GetWorkerConfigWithResponse request
	GetWorkerConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWorkerConfigResponse, error)

	// UpdateWorkerConfigWithBodyWithResponse request with any body
	UpdateWorkerConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateWorkerConfigResponse, error)

	UpdateWorkerConfigWithResponse(ctx context.Context, body UpdateWorkerConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateWorkerConfigResponse, error)

	// GetOperationWithResponse request
	GetOperationWithResponse(ctx context.Context, operationId OperationId, reqEditors ...RequestEditorFn) (*GetOperationResponse, error)

	// ListRecentOrdersWithResponse request
	ListRecentOrdersWithResponse(ctx context.Context, params *ListRecentOrdersParams, reqEditors ...RequestEditorFn) (*ListRecentOrdersResponse, error)

	// GetWorkerPolicyWithResponse request
	GetWorkerPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWorkerPolicyResponse, error)

	// RunOrderProcessingProbeWithBodyWithResponse request with any body
	RunOrderProcessingProbeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RunOrderProcessingProbeResponse, error)

	RunOrderProcessingProbeWithResponse(ctx context.Context, body RunOrderProcessingProbeJSONRequestBody, reqEditors ...RequestEditorFn) (*RunOrderProcessingProbeResponse, error)

	// GetQueueWithResponse request
	GetQueueWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueueResponse, error)

	// GetRuntimeWithResponse request
	GetRuntimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRuntimeResponse, error)

	// ReadyzWithResponse request
	ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error)
}

type CreateOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *Order
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateOrderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Order
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOrderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetWorkerConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WorkerConfig
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetWorkerConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkerConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetWorkerConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateWorkerConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OperationReceipt
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateWorkerConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateWorkerConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateWorkerConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OperationReceipt
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListRecentOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Orders []Order `json:"orders"`
	}
	JSONDefault *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListRecentOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRecentOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListRecentOrdersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetWorkerPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WorkerPolicy
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetWorkerPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkerPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetWorkerPolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RunOrderProcessingProbeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProbeResult
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RunOrderProcessingProbeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunOrderProcessingProbeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RunOrderProcessingProbeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetQueueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QueueSnapshot
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetQueueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQueueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetQueueResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRuntimeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeSnapshot
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetRuntimeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRuntimeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRuntimeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateOrderWithBodyWithResponse request with arbitrary body returning *CreateOrderResponse
func (c *ClientWithResponses) CreateOrderWithBodyWithResponse(ctx context.Context, params *CreateOrderParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error) {
	rsp, err := c.CreateOrderWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrderResponse(rsp)
}

func (c *ClientWithResponses) CreateOrderWithResponse(ctx context.Context, params *CreateOrderParams, body CreateOrderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrderResponse, error) {
	rsp, err := c.CreateOrder(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrderResponse(rsp)
}

// GetOrderWithResponse request returning *GetOrderResponse
func (c *ClientWithResponses) GetOrderWithResponse(ctx context.Context, orderId OrderId, reqEditors ...RequestEditorFn) (*GetOrderResponse, error) {
	rsp, err := c.GetOrder(ctx, orderId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrderResponse(rsp)
}

// HealthzWithResponse request returning *HealthzResponse
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// GetWorkerConfigWithResponse request returning *GetWorkerConfigResponse
func (c *ClientWithResponses) GetWorkerConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWorkerConfigResponse, error) {
	rsp, err := c.GetWorkerConfig(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkerConfigResponse(rsp)
}

// UpdateWorkerConfigWithBodyWithResponse request with arbitrary body returning *UpdateWorkerConfigResponse
func (c *ClientWithResponses) UpdateWorkerConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateWorkerConfigResponse, error) {
	rsp, err := c.UpdateWorkerConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateWorkerConfigResponse(rsp)
}

func (c *ClientWithResponses) UpdateWorkerConfigWithResponse(ctx context.Context, body UpdateWorkerConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateWorkerConfigResponse, error) {
	rsp, err := c.UpdateWorkerConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateWorkerConfigResponse(rsp)
}

// GetOperationWithResponse request returning *GetOperationResponse
func (c *ClientWithResponses) GetOperationWithResponse(ctx context.Context, operationId OperationId, reqEditors ...RequestEditorFn) (*GetOperationResponse, error) {
	rsp, err := c.GetOperation(ctx, operationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOperationResponse(rsp)
}

// ListRecentOrdersWithResponse request returning *ListRecentOrdersResponse
func (c *ClientWithResponses) ListRecentOrdersWithResponse(ctx context.Context, params *ListRecentOrdersParams, reqEditors ...RequestEditorFn) (*ListRecentOrdersResponse, error) {
	rsp, err := c.ListRecentOrders(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRecentOrdersResponse(rsp)
}

// GetWorkerPolicyWithResponse request returning *GetWorkerPolicyResponse
func (c *ClientWithResponses) GetWorkerPolicyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWorkerPolicyResponse, error) {
	rsp, err := c.GetWorkerPolicy(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkerPolicyResponse(rsp)
}

// RunOrderProcessingProbeWithBodyWithResponse request with arbitrary body returning *RunOrderProcessingProbeResponse
func (c *ClientWithResponses) RunOrderProcessingProbeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RunOrderProcessingProbeResponse, error) {
	rsp, err := c.RunOrderProcessingProbeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunOrderProcessingProbeResponse(rsp)
}

func (c *ClientWithResponses) RunOrderProcessingProbeWithResponse(ctx context.Context, body RunOrderProcessingProbeJSONRequestBody, reqEditors ...RequestEditorFn) (*RunOrderProcessingProbeResponse, error) {
	rsp, err := c.RunOrderProcessingProbe(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunOrderProcessingProbeResponse(rsp)
}

// GetQueueWithResponse request returning *GetQueueResponse
func (c *ClientWithResponses) GetQueueWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetQueueResponse, error) {
	rsp, err := c.GetQueue(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQueueResponse(rsp)
}

// GetRuntimeWithResponse request returning *GetRuntimeResponse
func (c *ClientWithResponses) GetRuntimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRuntimeResponse, error) {
	rsp, err := c.GetRuntime(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRuntimeResponse(rsp)
}

// ReadyzWithResponse request returning *ReadyzResponse
func (c *ClientWithResponses) ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error) {
	rsp, err := c.Readyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadyzResponse(rsp)
}

// ParseCreateOrderResponse parses an HTTP response from a CreateOrderWithResponse call
func ParseCreateOrderResponse(rsp *http.Response) (*CreateOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest Order
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetOrderResponse parses an HTTP response from a GetOrderWithResponse call
func ParseGetOrderResponse(rsp *http.Response) (*GetOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Order
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetWorkerConfigResponse parses an HTTP response from a GetWorkerConfigWithResponse call
func ParseGetWorkerConfigResponse(rsp *http.Response) (*GetWorkerConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkerConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WorkerConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateWorkerConfigResponse parses an HTTP response from a UpdateWorkerConfigWithResponse call
func ParseUpdateWorkerConfigResponse(rsp *http.Response) (*UpdateWorkerConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateWorkerConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OperationReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetOperationResponse parses an HTTP response from a GetOperationWithResponse call
func ParseGetOperationResponse(rsp *http.Response) (*GetOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OperationReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListRecentOrdersResponse parses an HTTP response from a ListRecentOrdersWithResponse call
func ParseListRecentOrdersResponse(rsp *http.Response) (*ListRecentOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRecentOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Orders []Order `json:"orders"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetWorkerPolicyResponse parses an HTTP response from a GetWorkerPolicyWithResponse call
func ParseGetWorkerPolicyResponse(rsp *http.Response) (*GetWorkerPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkerPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WorkerPolicy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRunOrderProcessingProbeResponse parses an HTTP response from a RunOrderProcessingProbeWithResponse call
func ParseRunOrderProcessingProbeResponse(rsp *http.Response) (*RunOrderProcessingProbeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunOrderProcessingProbeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProbeResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetQueueResponse parses an HTTP response from a GetQueueWithResponse call
func ParseGetQueueResponse(rsp *http.Response) (*GetQueueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQueueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QueueSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetRuntimeResponse parses an HTTP response from a GetRuntimeWithResponse call
func ParseGetRuntimeResponse(rsp *http.Response) (*GetRuntimeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRuntimeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseReadyzResponse parses an HTTP response from a ReadyzWithResponse call
func ParseReadyzResponse(rsp *http.Response) (*ReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
