//go:build go1.22

// Package faultgenerated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package faultgenerated

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ControlUnavailable ErrorCode = "control_unavailable"
	InternalError      ErrorCode = "internal_error"
	InvalidScenario    ErrorCode = "invalid_scenario"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ControlUnavailable:
		return true
	case InternalError:
		return true
	case InvalidScenario:
		return true
	default:
		return false
	}
}

// Defines values for FaultStateScenario.
const (
	FaultStateScenarioDependencyErrors FaultStateScenario = "dependency-errors"
	FaultStateScenarioSlowProcessing   FaultStateScenario = "slow-processing"
	FaultStateScenarioWorkerStopped    FaultStateScenario = "worker-stopped"
)

// Valid indicates whether the value is a known member of the FaultStateScenario enum.
func (e FaultStateScenario) Valid() bool {
	switch e {
	case FaultStateScenarioDependencyErrors:
		return true
	case FaultStateScenarioSlowProcessing:
		return true
	case FaultStateScenarioWorkerStopped:
		return true
	default:
		return false
	}
}

// Defines values for Scenario.
const (
	ScenarioDependencyErrors Scenario = "dependency-errors"
	ScenarioSlowProcessing   Scenario = "slow-processing"
	ScenarioWorkerStopped    Scenario = "worker-stopped"
)

// Valid indicates whether the value is a known member of the Scenario enum.
func (e Scenario) Valid() bool {
	switch e {
	case ScenarioDependencyErrors:
		return true
	case ScenarioSlowProcessing:
		return true
	case ScenarioWorkerStopped:
		return true
	default:
		return false
	}
}

// Defines values for ClearFaultParamsScenario.
const (
	ClearFaultParamsScenarioDependencyErrors ClearFaultParamsScenario = "dependency-errors"
	ClearFaultParamsScenarioSlowProcessing   ClearFaultParamsScenario = "slow-processing"
	ClearFaultParamsScenarioWorkerStopped    ClearFaultParamsScenario = "worker-stopped"
)

// Valid indicates whether the value is a known member of the ClearFaultParamsScenario enum.
func (e ClearFaultParamsScenario) Valid() bool {
	switch e {
	case ClearFaultParamsScenarioDependencyErrors:
		return true
	case ClearFaultParamsScenarioSlowProcessing:
		return true
	case ClearFaultParamsScenarioWorkerStopped:
		return true
	default:
		return false
	}
}

// Defines values for ActivateFaultParamsScenario.
const (
	ActivateFaultParamsScenarioDependencyErrors ActivateFaultParamsScenario = "dependency-errors"
	ActivateFaultParamsScenarioSlowProcessing   ActivateFaultParamsScenario = "slow-processing"
	ActivateFaultParamsScenarioWorkerStopped    ActivateFaultParamsScenario = "worker-stopped"
)

// Valid indicates whether the value is a known member of the ActivateFaultParamsScenario enum.
func (e ActivateFaultParamsScenario) Valid() bool {
	switch e {
	case ActivateFaultParamsScenarioDependencyErrors:
		return true
	case ActivateFaultParamsScenarioSlowProcessing:
		return true
	case ActivateFaultParamsScenarioWorkerStopped:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// FaultState defines model for FaultState.
type FaultState struct {
	Active    bool               `json:"active"`
	ChangedAt time.Time          `json:"changedAt"`
	Scenario  FaultStateScenario `json:"scenario"`
}

// FaultStateScenario defines model for FaultState.Scenario.
type FaultStateScenario string

// Scenario defines model for Scenario.
type Scenario string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// ClearFaultParamsScenario defines parameters for ClearFault.
type ClearFaultParamsScenario string

// ActivateFaultParamsScenario defines parameters for ActivateFault.
type ActivateFaultParamsScenario string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Restore all test controls to healthy defaults
	// (POST /faults/v1/reset)
	ResetFaults(w http.ResponseWriter, r *http.Request)
	// Clear one fixed fault
	// (DELETE /faults/v1/scenarios/{scenario})
	ClearFault(w http.ResponseWriter, r *http.Request, scenario ClearFaultParamsScenario)
	// Activate one fixed real processing fault through the private control socket
	// (POST /faults/v1/scenarios/{scenario}/activate)
	ActivateFault(w http.ResponseWriter, r *http.Request, scenario ActivateFaultParamsScenario)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ResetFaults operation middleware
func (siw *ServerInterfaceWrapper) ResetFaults(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetFaults(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearFault operation middleware
func (siw *ServerInterfaceWrapper) ClearFault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "scenario" -------------
	var scenario ClearFaultParamsScenario

	err = runtime.BindStyledParameterWithOptions("simple", "scenario", r.PathValue("scenario"), &scenario, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scenario", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearFault(w, r, scenario)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ActivateFault operation middleware
func (siw *ServerInterfaceWrapper) ActivateFault(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "scenario" -------------
	var scenario ActivateFaultParamsScenario

	err = runtime.BindStyledParameterWithOptions("simple", "scenario", r.PathValue("scenario"), &scenario, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scenario", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ActivateFault(w, r, scenario)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/faults/v1/reset", wrapper.ResetFaults)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/faults/v1/scenarios/{scenario}", wrapper.ClearFault)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/faults/v1/scenarios/{scenario}/activate", wrapper.ActivateFault)

	return m
}
