// Package grafanatools provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package grafanatools

import (
	"time"
)

// Defines values for CandidateType.
const (
	Counter   CandidateType = "counter"
	Gauge     CandidateType = "gauge"
	Histogram CandidateType = "histogram"
	Summary   CandidateType = "summary"
	Unknown   CandidateType = "unknown"
)

// Valid indicates whether the value is a known member of the CandidateType enum.
func (e CandidateType) Valid() bool {
	switch e {
	case Counter:
		return true
	case Gauge:
		return true
	case Histogram:
		return true
	case Summary:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for GetMetricLabelsInputSchemaMetricName.
const (
	NodeCpuSecondsTotal         GetMetricLabelsInputSchemaMetricName = "node_cpu_seconds_total"
	NodeLoad1                   GetMetricLabelsInputSchemaMetricName = "node_load1"
	NodeMemoryMemAvailableBytes GetMetricLabelsInputSchemaMetricName = "node_memory_MemAvailable_bytes"
)

// Valid indicates whether the value is a known member of the GetMetricLabelsInputSchemaMetricName enum.
func (e GetMetricLabelsInputSchemaMetricName) Valid() bool {
	switch e {
	case NodeCpuSecondsTotal:
		return true
	case NodeLoad1:
		return true
	case NodeMemoryMemAvailableBytes:
		return true
	default:
		return false
	}
}

// Defines values for QueryPrometheusInputSchemaMode.
const (
	Execute  QueryPrometheusInputSchemaMode = "execute"
	Validate QueryPrometheusInputSchemaMode = "validate"
)

// Valid indicates whether the value is a known member of the QueryPrometheusInputSchemaMode enum.
func (e QueryPrometheusInputSchemaMode) Valid() bool {
	switch e {
	case Execute:
		return true
	case Validate:
		return true
	default:
		return false
	}
}

// Defines values for QueryPrometheusOutputSchemaStatus.
const (
	Failed  QueryPrometheusOutputSchemaStatus = "failed"
	Success QueryPrometheusOutputSchemaStatus = "success"
)

// Valid indicates whether the value is a known member of the QueryPrometheusOutputSchemaStatus enum.
func (e QueryPrometheusOutputSchemaStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Candidate defines model for candidate.
type Candidate struct {
	Description string   `json:"description"`
	Labels      []string `json:"labels"`
	MetricName  string   `json:"metricName"`
	Score       float32  `json:"score"`
	Sources     []struct {
		Reference interface{} `json:"reference"`
		Type      interface{} `json:"type"`
	} `json:"sources"`
	Type CandidateType `json:"type"`
}

// CandidateType defines model for Candidate.Type.
type CandidateType string

// GetMetricLabelsInputSchema defines model for get-metric-labels.input.schema.
type GetMetricLabelsInputSchema struct {
	DatasourceUid interface{}                          `json:"datasourceUid"`
	MetricName    GetMetricLabelsInputSchemaMetricName `json:"metricName"`
}

// GetMetricLabelsInputSchemaMetricName defines model for GetMetricLabelsInputSchema.MetricName.
type GetMetricLabelsInputSchemaMetricName string

// GetMetricLabelsOutputSchema defines model for get-metric-labels.output.schema.
type GetMetricLabelsOutputSchema struct {
	LabelNames   []string            `json:"labelNames"`
	MetricName   string              `json:"metricName"`
	SampleValues map[string][]string `json:"sampleValues"`
}

// QueryPrometheusInputSchema defines model for query-prometheus.input.schema.
type QueryPrometheusInputSchema struct {
	DatasourceUid interface{}                    `json:"datasourceUid"`
	End           time.Time                      `json:"end"`
	Expression    string                         `json:"expression"`
	Mode          QueryPrometheusInputSchemaMode `json:"mode"`
	Start         time.Time                      `json:"start"`
	StepSeconds   int                            `json:"stepSeconds"`
}

// QueryPrometheusInputSchemaMode defines model for QueryPrometheusInputSchema.Mode.
type QueryPrometheusInputSchemaMode string

// QueryPrometheusOutputSchema defines model for query-prometheus.output.schema.
type QueryPrometheusOutputSchema struct {
	DurationMs int         `json:"durationMs"`
	ResultType interface{} `json:"resultType"`
	Series     []struct {
		Labels map[string]string `json:"labels"`
		Name   string            `json:"name"`
		Points []struct {
			Timestamp time.Time `json:"timestamp"`
			Value     float32   `json:"value"`
		} `json:"points"`
	} `json:"series"`
	Status     QueryPrometheusOutputSchemaStatus `json:"status"`
	Validation Validation                        `json:"validation"`
	Warnings   []string                          `json:"warnings"`
}

// QueryPrometheusOutputSchemaStatus defines model for QueryPrometheusOutputSchema.Status.
type QueryPrometheusOutputSchemaStatus string

// SearchMetricsInputSchema defines model for search-metrics.input.schema.
type SearchMetricsInputSchema struct {
	DatasourceUid interface{} `json:"datasourceUid"`
	Limit         int         `json:"limit"`
	Query         string      `json:"query"`
}

// SearchMetricsOutputSchema defines model for search-metrics.output.schema.
type SearchMetricsOutputSchema struct {
	Candidates []Candidate `json:"candidates"`
}

// Validation defines model for validation.
type Validation struct {
	Errors      []string `json:"errors"`
	LabelNames  []string `json:"labelNames"`
	MetricNames []string `json:"metricNames"`
	Valid       bool     `json:"valid"`
	Warnings    []string `json:"warnings"`
}

// GetMetricLabelsJSONRequestBody defines body for GetMetricLabels for application/json ContentType.
type GetMetricLabelsJSONRequestBody = GetMetricLabelsInputSchema

// QueryPrometheusJSONRequestBody defines body for QueryPrometheus for application/json ContentType.
type QueryPrometheusJSONRequestBody = QueryPrometheusInputSchema

// SearchMetricsJSONRequestBody defines body for SearchMetrics for application/json ContentType.
type SearchMetricsJSONRequestBody = SearchMetricsInputSchema
