// Package grafanatools provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package grafanatools

import (
	"time"
)

// Defines values for AssetRefKind.
const (
	Knowledge AssetRefKind = "knowledge"
	Playbook  AssetRefKind = "playbook"
	Skill     AssetRefKind = "skill"
)

// Valid indicates whether the value is a known member of the AssetRefKind enum.
func (e AssetRefKind) Valid() bool {
	switch e {
	case Knowledge:
		return true
	case Playbook:
		return true
	case Skill:
		return true
	default:
		return false
	}
}

// Defines values for BusinessProbeOutputResult.
const (
	BusinessProbeOutputResultCompleted BusinessProbeOutputResult = "completed"
	BusinessProbeOutputResultFailed    BusinessProbeOutputResult = "failed"
	BusinessProbeOutputResultTimedOut  BusinessProbeOutputResult = "timed_out"
)

// Valid indicates whether the value is a known member of the BusinessProbeOutputResult enum.
func (e BusinessProbeOutputResult) Valid() bool {
	switch e {
	case BusinessProbeOutputResultCompleted:
		return true
	case BusinessProbeOutputResultFailed:
		return true
	case BusinessProbeOutputResultTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for RecentOutcomesInputStatus.
const (
	RecentOutcomesInputStatusCompleted  RecentOutcomesInputStatus = "completed"
	RecentOutcomesInputStatusFailed     RecentOutcomesInputStatus = "failed"
	RecentOutcomesInputStatusProcessing RecentOutcomesInputStatus = "processing"
	RecentOutcomesInputStatusQueued     RecentOutcomesInputStatus = "queued"
)

// Valid indicates whether the value is a known member of the RecentOutcomesInputStatus enum.
func (e RecentOutcomesInputStatus) Valid() bool {
	switch e {
	case RecentOutcomesInputStatusCompleted:
		return true
	case RecentOutcomesInputStatusFailed:
		return true
	case RecentOutcomesInputStatusProcessing:
		return true
	case RecentOutcomesInputStatusQueued:
		return true
	default:
		return false
	}
}

// Defines values for RecentOutcomesOutputOrdersFailureReason.
const (
	DependencyUnavailable RecentOutcomesOutputOrdersFailureReason = "dependency_unavailable"
	RetryExhausted        RecentOutcomesOutputOrdersFailureReason = "retry_exhausted"
)

// Valid indicates whether the value is a known member of the RecentOutcomesOutputOrdersFailureReason enum.
func (e RecentOutcomesOutputOrdersFailureReason) Valid() bool {
	switch e {
	case DependencyUnavailable:
		return true
	case RetryExhausted:
		return true
	default:
		return false
	}
}

// Defines values for RecentOutcomesOutputOrdersStatus.
const (
	RecentOutcomesOutputOrdersStatusCompleted  RecentOutcomesOutputOrdersStatus = "completed"
	RecentOutcomesOutputOrdersStatusFailed     RecentOutcomesOutputOrdersStatus = "failed"
	RecentOutcomesOutputOrdersStatusProcessing RecentOutcomesOutputOrdersStatus = "processing"
	RecentOutcomesOutputOrdersStatusQueued     RecentOutcomesOutputOrdersStatus = "queued"
)

// Valid indicates whether the value is a known member of the RecentOutcomesOutputOrdersStatus enum.
func (e RecentOutcomesOutputOrdersStatus) Valid() bool {
	switch e {
	case RecentOutcomesOutputOrdersStatusCompleted:
		return true
	case RecentOutcomesOutputOrdersStatusFailed:
		return true
	case RecentOutcomesOutputOrdersStatusProcessing:
		return true
	case RecentOutcomesOutputOrdersStatusQueued:
		return true
	default:
		return false
	}
}

// Defines values for ResumeRunInputDiagnosisCandidateAction.
const (
	NoAction                 ResumeRunInputDiagnosisCandidateAction = "no_action"
	RestoreWorkerConcurrency ResumeRunInputDiagnosisCandidateAction = "restore_worker_concurrency"
)

// Valid indicates whether the value is a known member of the ResumeRunInputDiagnosisCandidateAction enum.
func (e ResumeRunInputDiagnosisCandidateAction) Valid() bool {
	switch e {
	case NoAction:
		return true
	case RestoreWorkerConcurrency:
		return true
	default:
		return false
	}
}

// Defines values for ResumeRunOutputStatus.
const (
	ResumeRunOutputStatusCompleted     ResumeRunOutputStatus = "completed"
	ResumeRunOutputStatusNeedsApproval ResumeRunOutputStatus = "needs_approval"
)

// Valid indicates whether the value is a known member of the ResumeRunOutputStatus enum.
func (e ResumeRunOutputStatus) Valid() bool {
	switch e {
	case ResumeRunOutputStatusCompleted:
		return true
	case ResumeRunOutputStatusNeedsApproval:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeOutputSupervisorStatus.
const (
	Degraded RuntimeOutputSupervisorStatus = "degraded"
	Running  RuntimeOutputSupervisorStatus = "running"
)

// Valid indicates whether the value is a known member of the RuntimeOutputSupervisorStatus enum.
func (e RuntimeOutputSupervisorStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// AssetGetInput defines model for AssetGetInput.
type AssetGetInput struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}

// AssetOutput defines model for AssetOutput.
type AssetOutput struct {
	Content string `json:"content"`
	Digest  string `json:"digest"`
	Id      string `json:"id"`
	Version string `json:"version"`
}

// AssetRef defines model for AssetRef.
type AssetRef struct {
	Digest  string       `json:"digest"`
	Id      string       `json:"id"`
	Kind    AssetRefKind `json:"kind"`
	Version string       `json:"version"`
}

// AssetRefKind defines model for AssetRef.Kind.
type AssetRefKind string

// BusinessProbeInput defines model for BusinessProbeInput.
type BusinessProbeInput struct {
	ProbeId string `json:"probeId"`
}

// BusinessProbeOutput defines model for BusinessProbeOutput.
type BusinessProbeOutput struct {
	CompletedAt *time.Time                `json:"completedAt"`
	DurationMs  int                       `json:"durationMs"`
	ProbeId     string                    `json:"probeId"`
	Result      BusinessProbeOutputResult `json:"result"`
}

// BusinessProbeOutputResult defines model for BusinessProbeOutput.Result.
type BusinessProbeOutputResult string

// EmptyInput defines model for EmptyInput.
type EmptyInput = map[string]interface{}

// GetOperationInput defines model for GetOperationInput.
type GetOperationInput struct {
	OperationId string `json:"operationId"`
}

// IntentDraft defines model for IntentDraft.
type IntentDraft struct {
	AfterConcurrency  interface{} `json:"afterConcurrency"`
	BeforeConcurrency interface{} `json:"beforeConcurrency"`
	CapabilityId      interface{} `json:"capabilityId"`
	ExpectedVersion   int         `json:"expectedVersion"`
	InstanceEpoch     string      `json:"instanceEpoch"`
	ObservedAt        time.Time   `json:"observedAt"`
	PlaybookDigest    string      `json:"playbookDigest"`
	PolicyDigest      string      `json:"policyDigest"`
	Risk              string      `json:"risk"`
	ServiceRef        interface{} `json:"serviceRef"`
}

// OperationOutput defines model for OperationOutput.
type OperationOutput struct {
	AfterConcurrency  interface{} `json:"afterConcurrency"`
	AfterVersion      int         `json:"afterVersion"`
	ApprovalId        string      `json:"approvalId"`
	BeforeConcurrency interface{} `json:"beforeConcurrency"`
	BeforeVersion     int         `json:"beforeVersion"`
	ExecutedAt        time.Time   `json:"executedAt"`
	InstanceEpoch     string      `json:"instanceEpoch"`
	IntentDigest      string      `json:"intentDigest"`
	OperationId       string      `json:"operationId"`
}

// PolicyOutput defines model for PolicyOutput.
type PolicyOutput struct {
	Digest              string      `json:"digest"`
	ExpectedConcurrency interface{} `json:"expectedConcurrency"`
	MaxConcurrency      interface{} `json:"maxConcurrency"`
	MinConcurrency      interface{} `json:"minConcurrency"`
	ServiceRef          interface{} `json:"serviceRef"`
	Version             interface{} `json:"version"`
}

// QueueOutput defines model for QueueOutput.
type QueueOutput struct {
	Capacity         interface{} `json:"capacity"`
	Depth            int         `json:"depth"`
	ObservedAt       time.Time   `json:"observedAt"`
	OldestAgeSeconds float32     `json:"oldestAgeSeconds"`
}

// RecentOutcomesInput defines model for RecentOutcomesInput.
type RecentOutcomesInput struct {
	Limit  *int                       `json:"limit,omitempty"`
	Status *RecentOutcomesInputStatus `json:"status,omitempty"`
}

// RecentOutcomesInputStatus defines model for RecentOutcomesInput.Status.
type RecentOutcomesInputStatus string

// RecentOutcomesOutput defines model for RecentOutcomesOutput.
type RecentOutcomesOutput struct {
	Orders []struct {
		CreatedAt     time.Time                                `json:"createdAt"`
		FailureReason *RecentOutcomesOutputOrdersFailureReason `json:"failureReason"`
		Id            string                                   `json:"id"`
		Status        RecentOutcomesOutputOrdersStatus         `json:"status"`
		UpdatedAt     time.Time                                `json:"updatedAt"`
	} `json:"orders"`
}

// RecentOutcomesOutputOrdersFailureReason defines model for RecentOutcomesOutput.Orders.FailureReason.
type RecentOutcomesOutputOrdersFailureReason string

// RecentOutcomesOutputOrdersStatus defines model for RecentOutcomesOutput.Orders.Status.
type RecentOutcomesOutputOrdersStatus string

// RecoveryMetricsOutput defines model for RecoveryMetricsOutput.
type RecoveryMetricsOutput struct {
	AcceptedDelta    float32     `json:"acceptedDelta"`
	CompletedDelta   float32     `json:"completedDelta"`
	ObservedAt       time.Time   `json:"observedAt"`
	OldestAgeSeconds float32     `json:"oldestAgeSeconds"`
	QueueDepth       float32     `json:"queueDepth"`
	WindowSeconds    interface{} `json:"windowSeconds"`
}

// ResolveAlertInput defines model for ResolveAlertInput.
type ResolveAlertInput struct {
	AlertName string            `json:"alertName"`
	Labels    map[string]string `json:"labels"`
	SourceId  string            `json:"sourceId"`
}

// ResolveAlertOutput defines model for ResolveAlertOutput.
type ResolveAlertOutput struct {
	MappingDigest   string      `json:"mappingDigest"`
	MappingId       string      `json:"mappingId"`
	PlaybookDigest  string      `json:"playbookDigest"`
	PlaybookId      string      `json:"playbookId"`
	PlaybookVersion string      `json:"playbookVersion"`
	ServiceRef      interface{} `json:"serviceRef"`
}

// RestoreWorkerInput defines model for RestoreWorkerInput.
type RestoreWorkerInput struct {
	ApprovalEvidence    string      `json:"approvalEvidence"`
	ApprovalId          string      `json:"approvalId"`
	ExpectedConcurrency interface{} `json:"expectedConcurrency"`
	ExpectedVersion     int         `json:"expectedVersion"`
	InstanceEpoch       string      `json:"instanceEpoch"`
	IntentDigest        string      `json:"intentDigest"`
	NewConcurrency      interface{} `json:"newConcurrency"`
	OperationId         string      `json:"operationId"`
}

// ResumeRunInput defines model for ResumeRunInput.
type ResumeRunInput struct {
	Checkpoint string `json:"checkpoint"`
	Diagnosis  struct {
		Alternatives      []string                               `json:"alternatives"`
		CandidateAction   ResumeRunInputDiagnosisCandidateAction `json:"candidateAction"`
		Confidence        float32                                `json:"confidence"`
		EvidenceRefs      []string                               `json:"evidenceRefs"`
		PrimaryHypothesis string                                 `json:"primaryHypothesis"`
	} `json:"diagnosis"`
}

// ResumeRunInputDiagnosisCandidateAction defines model for ResumeRunInput.Diagnosis.CandidateAction.
type ResumeRunInputDiagnosisCandidateAction string

// ResumeRunOutput defines model for ResumeRunOutput.
type ResumeRunOutput struct {
	Checkpoint  string                `json:"checkpoint"`
	IntentDraft *IntentDraft          `json:"intentDraft,omitempty"`
	Status      ResumeRunOutputStatus `json:"status"`
}

// ResumeRunOutputStatus defines model for ResumeRunOutput.Status.
type ResumeRunOutputStatus string

// RuntimeOutput defines model for RuntimeOutput.
type RuntimeOutput struct {
	InstanceEpoch    string                        `json:"instanceEpoch"`
	ServiceRef       interface{}                   `json:"serviceRef"`
	StartedAt        time.Time                     `json:"startedAt"`
	SupervisorStatus RuntimeOutputSupervisorStatus `json:"supervisorStatus"`
}

// RuntimeOutputSupervisorStatus defines model for RuntimeOutput.SupervisorStatus.
type RuntimeOutputSupervisorStatus string

// StartRunInput defines model for StartRunInput.
type StartRunInput struct {
	Digest     string      `json:"digest"`
	PlaybookId string      `json:"playbookId"`
	ServiceRef interface{} `json:"serviceRef"`
	Version    string      `json:"version"`
}

// StartRunOutput defines model for StartRunOutput.
type StartRunOutput struct {
	AssetRefs     []AssetRef  `json:"assetRefs"`
	CapabilityIds []string    `json:"capabilityIds"`
	Checkpoint    string      `json:"checkpoint"`
	Status        interface{} `json:"status"`
}

// WorkerOutput defines model for WorkerOutput.
type WorkerOutput struct {
	ActiveWorkers         int         `json:"activeWorkers"`
	ConfiguredConcurrency int         `json:"configuredConcurrency"`
	EffectiveConcurrency  int         `json:"effectiveConcurrency"`
	InflightOrders        int         `json:"inflightOrders"`
	InstanceEpoch         string      `json:"instanceEpoch"`
	ObservedAt            time.Time   `json:"observedAt"`
	ServiceRef            interface{} `json:"serviceRef"`
	Version               int         `json:"version"`
}
