/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/grafana.search_metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Type source for grafana.search_metrics */
        post: operations["searchMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grafana.get_metric_labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Type source for grafana.get_metric_labels */
        post: operations["getMetricLabels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grafana.query_prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Type source for grafana.query_prometheus */
        post: operations["queryPrometheus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchMetricsInput: components["schemas"]["search-metrics.input.schema"];
        SearchMetricsOutput: components["schemas"]["search-metrics.output.schema"];
        GetMetricLabelsInput: components["schemas"]["get-metric-labels.input.schema"];
        GetMetricLabelsOutput: components["schemas"]["get-metric-labels.output.schema"];
        QueryPrometheusInput: components["schemas"]["query-prometheus.input.schema"];
        QueryPrometheusOutput: components["schemas"]["query-prometheus.output.schema"];
        /** grafana.search_metrics input */
        "search-metrics.input.schema": {
            /** @constant */
            datasourceUid: "mock-prometheus";
            query: string;
            limit: number;
        };
        candidate: {
            metricName: string;
            /** @enum {string} */
            type: "counter" | "gauge" | "histogram" | "summary" | "unknown";
            description: string;
            labels: string[];
            score: number;
            sources: {
                /** @constant */
                type: "mock_fixture";
                /** @constant */
                reference: "node_exporter_overview";
            }[];
        };
        /** grafana.search_metrics output */
        "search-metrics.output.schema": {
            candidates: components["schemas"]["candidate"][];
            $defs: {
                candidate: {
                    metricName: string;
                    /** @enum {string} */
                    type: "counter" | "gauge" | "histogram" | "summary" | "unknown";
                    description: string;
                    labels: string[];
                    score: number;
                    sources: {
                        /** @constant */
                        type: "mock_fixture";
                        /** @constant */
                        reference: "node_exporter_overview";
                    }[];
                };
            };
        };
        /** grafana.get_metric_labels input */
        "get-metric-labels.input.schema": {
            /** @constant */
            datasourceUid: "mock-prometheus";
            /** @enum {string} */
            metricName: "node_cpu_seconds_total" | "node_memory_MemAvailable_bytes" | "node_load1";
        };
        /** grafana.get_metric_labels output */
        "get-metric-labels.output.schema": {
            metricName: string;
            labelNames: string[];
            sampleValues: {
                [key: string]: string[];
            };
        };
        /** grafana.query_prometheus input */
        "query-prometheus.input.schema": {
            /** @constant */
            datasourceUid: "mock-prometheus";
            expression: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            stepSeconds: number;
            /** @enum {string} */
            mode: "validate" | "execute";
        };
        validation: {
            valid: boolean;
            errors: string[];
            warnings: string[];
            metricNames: string[];
            labelNames: string[];
        };
        /** grafana.query_prometheus output */
        "query-prometheus.output.schema": {
            validation: components["schemas"]["validation"];
            /** @enum {string} */
            status: "success" | "failed";
            /** @constant */
            resultType: "matrix";
            series: {
                name: string;
                labels: {
                    [key: string]: string;
                };
                points: {
                    /** Format: date-time */
                    timestamp: string;
                    value: number;
                }[];
            }[];
            durationMs: number;
            warnings: string[];
            $defs: {
                validation: {
                    valid: boolean;
                    errors: string[];
                    warnings: string[];
                    metricNames: string[];
                    labelNames: string[];
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["search-metrics.input.schema"];
            };
        };
        responses: {
            /** @description Tool output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["search-metrics.output.schema"];
                };
            };
        };
    };
    getMetricLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["get-metric-labels.input.schema"];
            };
        };
        responses: {
            /** @description Tool output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["get-metric-labels.output.schema"];
                };
            };
        };
    };
    queryPrometheus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["query-prometheus.input.schema"];
            };
        };
        responses: {
            /** @description Tool output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["query-prometheus.output.schema"];
                };
            };
        };
    };
}
