/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/knowledge.get_document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["knowledgeGet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills.get_skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["skillGet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playbook.resolve_alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["resolveAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playbook.start_run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playbook.resume_run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getRuntime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_queue_snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_worker_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_worker_policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_recent_outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getRecent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_operation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.restore_worker_concurrency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["restoreWorkerConcurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.get_recovery_metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["getRecoveryMetrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order_service.run_business_probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: components["x-operations"]["runBusinessProbe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetGetInput: {
            id: string;
            version: string;
        };
        ResolveAlertInput: {
            sourceId: string;
            alertName: string;
            labels: {
                [key: string]: string;
            };
        };
        StartRunInput: {
            playbookId: string;
            version: string;
            digest: string;
            /** @constant */
            serviceRef: "order-demo";
        };
        ResumeRunInput: {
            checkpoint: string;
            diagnosis: {
                primaryHypothesis: string;
                evidenceRefs: string[];
                alternatives: string[];
                confidence: number;
                /** @enum {string} */
                candidateAction: "restore_worker_concurrency" | "no_action";
            };
        };
        EmptyInput: Record<string, never>;
        RecentOutcomesInput: {
            /** @enum {string} */
            status?: "queued" | "processing" | "completed" | "failed";
            /** @default 10 */
            limit: number;
        };
        GetOperationInput: {
            operationId: string;
        };
        RestoreWorkerInput: {
            operationId: string;
            instanceEpoch: string;
            expectedVersion: number;
            /** @constant */
            expectedConcurrency: 0;
            /** @constant */
            newConcurrency: 2;
            intentDigest: string;
            approvalId: string;
            approvalEvidence: string;
        };
        BusinessProbeInput: {
            probeId: string;
        };
        AssetOutput: {
            id: string;
            version: string;
            digest: string;
            content: string;
        };
        ResolveAlertOutput: {
            mappingId: string;
            mappingDigest: string;
            playbookId: string;
            playbookVersion: string;
            playbookDigest: string;
            /** @constant */
            serviceRef: "order-demo";
        };
        StartRunOutput: {
            /** @constant */
            status: "needs_agent";
            checkpoint: string;
            assetRefs: components["schemas"]["AssetRef"][];
            capabilityIds: string[];
        };
        ResumeRunOutput: {
            /** @enum {string} */
            status: "needs_approval" | "completed";
            checkpoint: string;
            intentDraft?: components["schemas"]["IntentDraft"];
        };
        RuntimeOutput: {
            /** @constant */
            serviceRef: "order-demo";
            instanceEpoch: string;
            /** Format: date-time */
            startedAt: string;
            /** @enum {string} */
            supervisorStatus: "running" | "degraded";
        };
        QueueOutput: {
            depth: number;
            /** @constant */
            capacity: 100;
            oldestAgeSeconds: number;
            /** Format: date-time */
            observedAt: string;
        };
        WorkerOutput: {
            /** @constant */
            serviceRef: "order-demo";
            instanceEpoch: string;
            configuredConcurrency: number;
            effectiveConcurrency: number;
            activeWorkers: number;
            inflightOrders: number;
            version: number;
            /** Format: date-time */
            observedAt: string;
        };
        PolicyOutput: {
            /** @constant */
            serviceRef: "order-demo";
            /** @constant */
            expectedConcurrency: 2;
            /** @constant */
            minConcurrency: 1;
            /** @constant */
            maxConcurrency: 4;
            /** @constant */
            version: "v1";
            digest: string;
        };
        RecentOutcomesOutput: {
            orders: {
                id: string;
                /** @enum {string} */
                status: "queued" | "processing" | "completed" | "failed";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                failureReason: ("dependency_unavailable" | "retry_exhausted") | null;
            }[];
        };
        OperationOutput: {
            operationId: string;
            instanceEpoch: string;
            beforeVersion: number;
            afterVersion: number;
            /** @constant */
            beforeConcurrency: 0;
            /** @constant */
            afterConcurrency: 2;
            intentDigest: string;
            approvalId: string;
            /** Format: date-time */
            executedAt: string;
        };
        RecoveryMetricsOutput: {
            /** @constant */
            windowSeconds: 30;
            acceptedDelta: number;
            completedDelta: number;
            queueDepth: number;
            oldestAgeSeconds: number;
            /** Format: date-time */
            observedAt: string;
        };
        BusinessProbeOutput: {
            probeId: string;
            /** @enum {string} */
            result: "completed" | "timed_out" | "failed";
            durationMs: number;
            completedAt: string | null;
        };
        AssetRef: {
            /** @enum {string} */
            kind: "knowledge" | "skill" | "playbook";
            id: string;
            version: string;
            digest: string;
        };
        IntentDraft: {
            /** @constant */
            capabilityId: "order_service.restore_worker_concurrency";
            /** @constant */
            serviceRef: "order-demo";
            instanceEpoch: string;
            expectedVersion: number;
            /** Format: date-time */
            observedAt: string;
            policyDigest: string;
            playbookDigest: string;
            /** @constant */
            beforeConcurrency: 0;
            /** @constant */
            afterConcurrency: 2;
            risk: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
