/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report process liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report storage and MCP dependency readiness */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Session with Plugin-derived RequestContext */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped Session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant-scoped Session Messages by stable descending keyset page */
        get: operations["listSessionMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant-scoped Session Tasks by stable descending keyset page */
        get: operations["listSessionTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asynchronous tenant-scoped Task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped Task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay and follow durable tenant-scoped TaskEvents */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}/events/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a finite durable TaskEvent replay page with a fixed target sequence */
        get: operations["replayTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionRequest: components["schemas"]["create-session-request.schema"];
        CreateTaskRequest: components["schemas"]["create-task-request.schema"];
        Session: components["schemas"]["session.schema"];
        Message: components["schemas"]["message.schema"];
        Task: components["schemas"]["task.schema"];
        MessagePage: components["schemas"]["message-page.schema"];
        TaskPage: components["schemas"]["task-page.schema"];
        TaskEventReplayPage: components["schemas"]["task-event-replay-page.schema"];
        Chart: components["schemas"]["chart.schema"];
        ChartExecution: components["schemas"]["execution.schema"];
        TaskEvent: components["schemas"]["task-events.schema"];
        ErrorEnvelope: components["schemas"]["error.schema"];
        error: {
            /** @enum {string} */
            code: "invalid_argument" | "unauthenticated" | "permission_denied" | "resource_not_found" | "resource_conflict" | "invalid_state_transition" | "adapter_not_configured" | "dependency_unavailable" | "tool_not_supported" | "tool_timeout" | "schema_validation_failed" | "idempotency_conflict" | "execution_interrupted" | "internal_error" | "not_implemented";
            message: string;
            retryable: boolean;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        "error.schema": {
            error: components["schemas"]["error"];
            $defs: {
                error: {
                    /** @enum {string} */
                    code: "invalid_argument" | "unauthenticated" | "permission_denied" | "resource_not_found" | "resource_conflict" | "invalid_state_transition" | "adapter_not_configured" | "dependency_unavailable" | "tool_not_supported" | "tool_timeout" | "schema_validation_failed" | "idempotency_conflict" | "execution_interrupted" | "internal_error" | "not_implemented";
                    message: string;
                    retryable: boolean;
                    requestId: string;
                    details?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** CreateSessionRequest */
        "create-session-request.schema": {
            title?: string;
        };
        /** AnalysisSession */
        "session.schema": {
            id: string;
            tenantId: string;
            title: string;
            /** @enum {string} */
            status: "active";
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        /** Message */
        "message.schema": {
            id: string;
            sessionId: string;
            taskId: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** MessagePage */
        "message-page.schema": {
            items: components["schemas"]["message.schema"][];
            nextPageToken: string | null;
        };
        /** AnalysisTask */
        "task.schema": {
            id: string;
            sessionId: string;
            /** @enum {string} */
            status: "created" | "planning" | "running_tools" | "validating" | "completed" | "failed";
            inputMessageId: string;
            /** @enum {string} */
            datasourceUid: "prometheus-main";
            timeRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            queryPlan: {
                views: ("cpu" | "memory" | "load")[];
                /** @enum {integer} */
                stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                /** @enum {integer} */
                cpuRateWindowSeconds: 30 | 60 | 300;
            };
            latestSequence: number;
            error: ({
                code: string;
                message: string;
                retryable: boolean;
                requestId: string;
            } & {
                [key: string]: unknown;
            }) | null;
            /** Format: date-time */
            createdAt: string;
            startedAt: string | null;
            completedAt: string | null;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        /** TaskPage */
        "task-page.schema": {
            items: components["schemas"]["task.schema"][];
            nextPageToken: string | null;
        };
        /** CreateTaskRequest */
        "create-task-request.schema": {
            sessionId: string;
            message: string;
            analysisContext: {
                /** @enum {string} */
                datasourceUid: "prometheus-main";
                timeRange?: {
                    /** Format: date-time */
                    from: string;
                    /** Format: date-time */
                    to: string;
                } | {
                    relativeDuration: string;
                };
                resolution?: {
                    /** @constant */
                    mode: "auto";
                } | {
                    /** @enum {integer} */
                    stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                };
            };
        };
        taskSnapshot: {
            id: string;
            sessionId: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        taskEventError: {
            code: string;
            message: string;
            retryable: boolean;
            requestId: string;
        } & {
            [key: string]: unknown;
        };
        message: {
            id: string;
            sessionId: string;
            taskId: string;
            role: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        candidate: {
            metricName: string;
            type: string;
            description: string;
            labels: unknown[];
            score: number;
            sources: unknown[];
        } & {
            [key: string]: unknown;
        };
        chart: {
            id: string;
            taskId: string;
            title: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        execution: {
            id: string;
            status: string;
            series: unknown[];
            seriesCount: number;
        } & {
            [key: string]: unknown;
        };
        taskCreated: {
            task: components["schemas"]["taskSnapshot"];
        };
        statusChanged: {
            /** @enum {string} */
            previousStatus: "created" | "planning" | "running_tools" | "validating" | "completed" | "failed";
            /** @enum {string} */
            status: "created" | "planning" | "running_tools" | "validating" | "completed" | "failed";
            error?: components["schemas"]["taskEventError"];
        };
        assistantStarted: {
            messageId: string;
            /** @constant */
            role: "assistant";
        };
        assistantDelta: {
            messageId: string;
            delta: string;
            ordinal: number;
        };
        assistantCompleted: {
            message: components["schemas"]["message"];
        };
        toolStarted: {
            toolCallId: string;
            toolName: string;
            /** @constant */
            toolVersion: "v1";
            inputSummary: {
                [key: string]: unknown;
            };
        };
        toolCompleted: {
            toolCallId: string;
            toolName: string;
            durationMs: number;
            outputSummary: {
                [key: string]: unknown;
            };
        };
        toolFailed: {
            toolCallId: string;
            toolName: string;
            durationMs: number;
            error: components["schemas"]["taskEventError"];
        };
        metricCandidates: {
            candidates: components["schemas"]["candidate"][];
        };
        chartCreated: {
            chart: components["schemas"]["chart"];
        };
        chartExecutionCompleted: {
            chartId: string;
            execution: components["schemas"]["execution"];
            /** @constant */
            chartStatus: "ready";
        };
        taskCompleted: {
            task: components["schemas"]["taskSnapshot"];
        };
        taskFailed: {
            task: components["schemas"]["taskSnapshot"];
            error: components["schemas"]["taskEventError"];
        };
        /** TaskEvent */
        "task-events.schema": {
            eventId: string;
            taskId: string;
            sessionId: string;
            sequence: number;
            /** @enum {string} */
            type: "task.created" | "task.status_changed" | "assistant.message.started" | "assistant.message.delta" | "assistant.message.completed" | "tool.started" | "tool.completed" | "tool.failed" | "metric.candidates_created" | "chart.created" | "chart.execution_completed" | "task.completed" | "task.failed";
            /** Format: date-time */
            timestamp: string;
            payload: Record<string, never>;
            $defs: {
                taskEventError: {
                    code: string;
                    message: string;
                    retryable: boolean;
                    requestId: string;
                } & {
                    [key: string]: unknown;
                };
                taskSnapshot: {
                    id: string;
                    sessionId: string;
                    status: string;
                } & {
                    [key: string]: unknown;
                };
                message: {
                    id: string;
                    sessionId: string;
                    taskId: string;
                    role: string;
                    content: string;
                    /** Format: date-time */
                    createdAt: string;
                } & {
                    [key: string]: unknown;
                };
                candidate: {
                    metricName: string;
                    type: string;
                    description: string;
                    labels: unknown[];
                    score: number;
                    sources: unknown[];
                } & {
                    [key: string]: unknown;
                };
                chart: {
                    id: string;
                    taskId: string;
                    title: string;
                    status: string;
                } & {
                    [key: string]: unknown;
                };
                execution: {
                    id: string;
                    status: string;
                    series: unknown[];
                    seriesCount: number;
                } & {
                    [key: string]: unknown;
                };
                taskCreated: {
                    task: components["schemas"]["taskSnapshot"];
                };
                statusChanged: {
                    /** @enum {string} */
                    previousStatus: "created" | "planning" | "running_tools" | "validating" | "completed" | "failed";
                    /** @enum {string} */
                    status: "created" | "planning" | "running_tools" | "validating" | "completed" | "failed";
                    error?: components["schemas"]["taskEventError"];
                };
                assistantStarted: {
                    messageId: string;
                    /** @constant */
                    role: "assistant";
                };
                assistantDelta: {
                    messageId: string;
                    delta: string;
                    ordinal: number;
                };
                assistantCompleted: {
                    message: components["schemas"]["message"];
                };
                toolStarted: {
                    toolCallId: string;
                    toolName: string;
                    /** @constant */
                    toolVersion: "v1";
                    inputSummary: {
                        [key: string]: unknown;
                    };
                };
                toolCompleted: {
                    toolCallId: string;
                    toolName: string;
                    durationMs: number;
                    outputSummary: {
                        [key: string]: unknown;
                    };
                };
                toolFailed: {
                    toolCallId: string;
                    toolName: string;
                    durationMs: number;
                    error: components["schemas"]["taskEventError"];
                };
                metricCandidates: {
                    candidates: components["schemas"]["candidate"][];
                };
                chartCreated: {
                    chart: components["schemas"]["chart"];
                };
                chartExecutionCompleted: {
                    chartId: string;
                    execution: components["schemas"]["execution"];
                    /** @constant */
                    chartStatus: "ready";
                };
                taskCompleted: {
                    task: components["schemas"]["taskSnapshot"];
                };
                taskFailed: {
                    task: components["schemas"]["taskSnapshot"];
                    error: components["schemas"]["taskEventError"];
                };
            };
        } & ({
            /** @constant */
            type?: "task.created";
            payload?: components["schemas"]["taskCreated"];
        } | {
            /** @constant */
            type?: "task.status_changed";
            payload?: components["schemas"]["statusChanged"];
        } | {
            /** @constant */
            type?: "assistant.message.started";
            payload?: components["schemas"]["assistantStarted"];
        } | {
            /** @constant */
            type?: "assistant.message.delta";
            payload?: components["schemas"]["assistantDelta"];
        } | {
            /** @constant */
            type?: "assistant.message.completed";
            payload?: components["schemas"]["assistantCompleted"];
        } | {
            /** @constant */
            type?: "tool.started";
            payload?: components["schemas"]["toolStarted"];
        } | {
            /** @constant */
            type?: "tool.completed";
            payload?: components["schemas"]["toolCompleted"];
        } | {
            /** @constant */
            type?: "tool.failed";
            payload?: components["schemas"]["toolFailed"];
        } | {
            /** @constant */
            type?: "metric.candidates_created";
            payload?: components["schemas"]["metricCandidates"];
        } | {
            /** @constant */
            type?: "chart.created";
            payload?: components["schemas"]["chartCreated"];
        } | {
            /** @constant */
            type?: "chart.execution_completed";
            payload?: components["schemas"]["chartExecutionCompleted"];
        } | {
            /** @constant */
            type?: "task.completed";
            payload?: components["schemas"]["taskCompleted"];
        } | {
            /** @constant */
            type?: "task.failed";
            payload?: components["schemas"]["taskFailed"];
        });
        /** TaskEventReplayPage */
        "task-event-replay-page.schema": {
            items: components["schemas"]["task-events.schema"][];
            targetSequence: number;
            nextPageToken: string | null;
        };
        query: {
            refId: string;
            expression: string;
            legend: string;
            /** @enum {string} */
            datasourceUid: "prometheus-main";
            timeRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @enum {integer} */
            stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
        };
        /** ChartDraft */
        "chart.schema": {
            id: string;
            sessionId: string;
            taskId: string;
            title: string;
            /** @constant */
            visualization: "timeseries";
            unit: string;
            queries: components["schemas"]["query"][];
            /** @enum {string} */
            status: "proposed" | "ready";
            latestExecutionId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
            $defs: {
                query: {
                    refId: string;
                    expression: string;
                    legend: string;
                    /** @enum {string} */
                    datasourceUid: "prometheus-main";
                    timeRange: {
                        /** Format: date-time */
                        from: string;
                        /** Format: date-time */
                        to: string;
                    };
                    /** @enum {integer} */
                    stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                };
            };
        };
        /** ChartExecution */
        "execution.schema": {
            id: string;
            queryRefId: string;
            /** @enum {string} */
            status: "success" | "failed";
            seriesCount: number;
            durationMs: number;
            sampleRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            actualSampleRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            } | null;
            series: {
                name: string;
                labels: {
                    [key: string]: string;
                };
                points: {
                    /** Format: date-time */
                    timestamp: string;
                    value: number;
                }[];
            }[];
            warnings: string[];
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Structured domain error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["error.schema"];
            };
        };
    };
    parameters: {
        SessionId: string;
        TaskId: string;
        IdempotencyKey: string;
        RequestId: string;
        TraceId: string;
        TraceParent: string;
        AfterSequence: number;
        PageSizeMessages: number;
        PageSizeTasks: number;
        PageSizeReplay: number;
        PageToken: string;
        LastEventId: number;
        TenantId: string;
        OrgId: string;
        UserId: string;
        /** @description Comma-separated, trimmed and de-duplicated roles. */
        Roles: string;
        /** @description Comma-separated permissions; must include datasources:query for this profile. */
        Permissions: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migrations, storage and MCP dependency are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ErrorResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["create-session-request.schema"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["session.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["session.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSessionMessages: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeMessages"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["message-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSessionTasks: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeTasks"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["create-task-request.schema"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: {
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "Last-Event-ID"?: components["parameters"]["LastEventId"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable TaskEvent stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["task-events.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    replayTaskEvents: {
        parameters: {
            query?: {
                afterSequence?: components["parameters"]["AfterSequence"];
                pageSize?: components["parameters"]["PageSizeReplay"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finite replay page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task-event-replay-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
