/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/v1/alerts/grafana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a bounded Grafana Alerting webhook after source and HMAC verification
         * @description This machine endpoint does not accept Grafana user identity headers. The signature is lowercase hexadecimal HMAC-SHA256 over `timestamp + ":" + rawBody`.
         */
        post: operations["ingestGrafanaAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report process liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report storage and MCP dependency readiness */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current creator's non-empty Sessions by recent activity */
        get: operations["listSessions"];
        put?: never;
        /** Create a Session with Plugin-derived RequestContext */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped Session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant-scoped Session Messages by stable descending keyset page */
        get: operations["listSessionMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant-scoped Session Tasks by stable descending keyset page */
        get: operations["listSessionTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an asynchronous tenant-scoped Task */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant-scoped Task */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization-visible Incident Tasks by recent activity */
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current pending or decided Approval for an Incident Task */
        get: operations["getTaskApproval"];
        put?: never;
        /** Admin decision over the exact immutable Incident Intent */
        post: operations["decideTaskApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay and follow durable tenant-scoped TaskEvents */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{taskId}/events/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a finite durable TaskEvent replay page with a fixed target sequence */
        get: operations["replayTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionRequest: components["schemas"]["create-session-request.schema"];
        CreateTaskRequest: components["schemas"]["create-task-request.schema"];
        Session: components["schemas"]["session.schema"];
        SessionPage: components["schemas"]["session-page.schema"];
        Message: components["schemas"]["message.schema"];
        Task: components["schemas"]["task.schema"];
        MessagePage: components["schemas"]["message-page.schema"];
        TaskPage: components["schemas"]["task-page.schema"];
        TaskEventReplayPage: components["schemas"]["task-event-replay-page.schema"];
        Chart: components["schemas"]["chart.schema"];
        ChartExecution: components["schemas"]["execution.schema"];
        TaskEvent: components["schemas"]["task-events.schema"];
        ErrorEnvelope: components["schemas"]["error.schema"];
        GrafanaAlertWebhook: components["schemas"]["grafana-alert-webhook.schema"];
        AlertIngressResponse: components["schemas"]["alert-ingress-response.schema"];
        Approval: components["schemas"]["approval.schema"];
        DecideApprovalRequest: components["schemas"]["decide-approval-request.schema"];
        labels: {
            [key: string]: string;
        };
        alert: {
            /** @enum {string} */
            status: "firing" | "resolved";
            labels: components["schemas"]["labels"] & {
                alertname: string;
                service_ref: string;
            };
            annotations: components["schemas"]["labels"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            generatorURL?: string;
            fingerprint: string;
            silenceURL?: string;
            dashboardURL?: string;
            panelURL?: string;
            imageURL?: string;
            values?: {
                [key: string]: number | string;
            };
            valueString?: string;
        };
        /** GrafanaAlertWebhook */
        "grafana-alert-webhook.schema": {
            receiver: string;
            /** @enum {string} */
            status: "firing" | "resolved";
            orgId?: number;
            alerts: components["schemas"]["alert"][];
            groupLabels?: components["schemas"]["labels"];
            commonLabels?: components["schemas"]["labels"];
            commonAnnotations?: components["schemas"]["labels"];
            externalURL?: string;
            appVersion?: string;
            version?: string;
            groupKey?: string;
            truncatedAlerts?: number;
            title?: string;
            state?: string;
            message?: string;
            $defs: {
                labels: {
                    [key: string]: string;
                };
                alert: {
                    /** @enum {string} */
                    status: "firing" | "resolved";
                    labels: components["schemas"]["labels"] & {
                        alertname: string;
                        service_ref: string;
                    };
                    annotations: components["schemas"]["labels"];
                    /** Format: date-time */
                    startsAt: string;
                    /** Format: date-time */
                    endsAt: string;
                    generatorURL?: string;
                    fingerprint: string;
                    silenceURL?: string;
                    dashboardURL?: string;
                    panelURL?: string;
                    imageURL?: string;
                    values?: {
                        [key: string]: number | string;
                    };
                    valueString?: string;
                };
            };
        };
        error: {
            /** @enum {string} */
            code: "invalid_argument" | "unauthenticated" | "permission_denied" | "resource_not_found" | "resource_conflict" | "invalid_state_transition" | "adapter_not_configured" | "dependency_unavailable" | "tool_not_supported" | "tool_timeout" | "schema_validation_failed" | "idempotency_conflict" | "execution_interrupted" | "target_precondition_failed" | "approval_required" | "approval_expired" | "internal_error" | "not_implemented";
            message: string;
            retryable: boolean;
            requestId: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorEnvelope */
        "error.schema": {
            error: components["schemas"]["error"];
            $defs: {
                error: {
                    /** @enum {string} */
                    code: "invalid_argument" | "unauthenticated" | "permission_denied" | "resource_not_found" | "resource_conflict" | "invalid_state_transition" | "adapter_not_configured" | "dependency_unavailable" | "tool_not_supported" | "tool_timeout" | "schema_validation_failed" | "idempotency_conflict" | "execution_interrupted" | "target_precondition_failed" | "approval_required" | "approval_expired" | "internal_error" | "not_implemented";
                    message: string;
                    retryable: boolean;
                    requestId: string;
                    details?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** AlertIngressResponse */
        "alert-ingress-response.schema": {
            accepted: number;
            duplicate: number;
            taskIds: string[];
        };
        /** Session */
        "session.schema": {
            id: string;
            tenantId: string;
            orgId: string;
            /** @enum {string} */
            kind: "private" | "org_incident";
            title: string;
            /** @enum {string} */
            status: "active";
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        /** SessionPage */
        "session-page.schema": {
            items: components["schemas"]["session.schema"][];
            nextPageToken: string | null;
        };
        /** CreateSessionRequest */
        "create-session-request.schema": {
            title?: string;
        };
        /** Message */
        "message.schema": {
            id: string;
            sessionId: string;
            taskId: string;
            /** @enum {string} */
            role: "user" | "assistant" | "trigger";
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** MessagePage */
        "message-page.schema": {
            items: components["schemas"]["message.schema"][];
            nextPageToken: string | null;
        };
        /** IncidentPlan */
        "incident-plan.schema": {
            sourceId: string;
            alertName: string;
            alertFingerprint: string;
            serviceRef: string;
            labels: {
                [key: string]: string;
            };
            mapping: {
                id: string;
                digest: string;
            };
            playbook: {
                id: string;
                version: string;
                digest: string;
            };
            assetRefs: {
                /** @enum {string} */
                kind: "knowledge" | "skill" | "playbook" | "alert_mapping";
                id: string;
                version: string;
                digest: string;
            }[];
            /** @enum {string} */
            phase: "load_assets" | "observe" | "needs_agent" | "prepare" | "needs_approval" | "execute" | "verify_runtime" | "verify_metrics" | "verify_business" | "completed" | "no_action";
            diagnosis: null | {
                /** @enum {string} */
                primaryHypothesis: "worker_stopped" | "slow_processing" | "dependency_errors" | "healthy" | "insufficient_evidence";
                evidenceRefs: string[];
                alternativeHypotheses: string[];
                confidence: number;
                /** @enum {string} */
                candidateAction: "restore_worker_concurrency" | "no_action";
            };
            intent: null | {
                id: string;
                digest: string;
                /** @constant */
                capabilityId: "order_service.restore_worker_concurrency";
                serviceRef: string;
                instanceEpoch: string;
                expectedVersion: number;
                /** @constant */
                beforeConcurrency: 0;
                /** @constant */
                afterConcurrency: 2;
                /** @enum {string} */
                risk: "low";
                /** Format: date-time */
                createdAt: string;
            };
        };
        /** Task */
        "task.schema": {
            id: string;
            /** @enum {string} */
            kind: "metric_analysis" | "incident_remediation";
            sessionId: string;
            /** @enum {string} */
            status: "created" | "planning" | "running_tools" | "waiting_approval" | "executing" | "reconciling" | "validating" | "completed" | "failed" | "cancelled";
            inputMessageId: string;
            /** @enum {string} */
            datasourceUid?: "prometheus-main";
            timeRange?: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            queryPlan?: {
                views: ("cpu" | "memory" | "load")[];
                /** @enum {integer} */
                stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                /** @enum {integer} */
                cpuRateWindowSeconds: 30 | 60 | 300;
            };
            incidentPlan?: components["schemas"]["incident-plan.schema"];
            latestSequence: number;
            error: ({
                code: string;
                message: string;
                retryable: boolean;
                requestId: string;
            } & {
                [key: string]: unknown;
            }) | null;
            /** Format: date-time */
            createdAt: string;
            startedAt: string | null;
            completedAt: string | null;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        } & (unknown & unknown);
        /** TaskPage */
        "task-page.schema": {
            items: components["schemas"]["task.schema"][];
            nextPageToken: string | null;
        };
        /** CreateTaskRequest */
        "create-task-request.schema": {
            sessionId: string;
            message: string;
            analysisContext: {
                /** @enum {string} */
                datasourceUid: "prometheus-main";
                timeRange?: {
                    /** Format: date-time */
                    from: string;
                    /** Format: date-time */
                    to: string;
                } | {
                    relativeDuration: string;
                };
                resolution?: {
                    /** @constant */
                    mode: "auto";
                } | {
                    /** @enum {integer} */
                    stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                };
            };
        };
        /** Approval */
        "approval.schema": {
            id: string;
            taskId: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "expired";
            intentDigest: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            expiresAt: string;
            decidedAt: string | null;
            decidedBy: string | null;
            decisionReason: string | null;
            version: number;
        };
        /** DecideApprovalRequest */
        "decide-approval-request.schema": {
            /** @enum {string} */
            decision: "approve" | "reject";
            reason: string;
            expectedTaskVersion: number;
            expectedApprovalVersion: number;
            intentDigest: string;
        };
        taskSnapshot: {
            id: string;
            sessionId: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        taskEventError: {
            code: string;
            message: string;
            retryable: boolean;
            requestId: string;
        } & {
            [key: string]: unknown;
        };
        message: {
            id: string;
            sessionId: string;
            taskId: string;
            role: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
        } & {
            [key: string]: unknown;
        };
        candidate: {
            metricName: string;
            type: string;
            description: string;
            labels: unknown[];
            score: number;
            sources: unknown[];
        } & {
            [key: string]: unknown;
        };
        chart: {
            id: string;
            taskId: string;
            title: string;
            status: string;
        } & {
            [key: string]: unknown;
        };
        execution: {
            id: string;
            status: string;
            series: unknown[];
            seriesCount: number;
        } & {
            [key: string]: unknown;
        };
        taskCreated: {
            task: components["schemas"]["taskSnapshot"];
        };
        statusChanged: {
            /** @enum {string} */
            previousStatus: "created" | "planning" | "running_tools" | "waiting_approval" | "executing" | "reconciling" | "validating" | "completed" | "failed" | "cancelled";
            /** @enum {string} */
            status: "created" | "planning" | "running_tools" | "waiting_approval" | "executing" | "reconciling" | "validating" | "completed" | "failed" | "cancelled";
            error?: components["schemas"]["taskEventError"];
        };
        assistantStarted: {
            messageId: string;
            /** @constant */
            role: "assistant";
        };
        assistantDelta: {
            messageId: string;
            delta: string;
            ordinal: number;
        };
        assistantCompleted: {
            message: components["schemas"]["message"];
        };
        toolStarted: {
            toolCallId: string;
            toolName: string;
            /** @constant */
            toolVersion: "v1";
            inputSummary: {
                [key: string]: unknown;
            };
        };
        toolCompleted: {
            toolCallId: string;
            toolName: string;
            durationMs: number;
            outputSummary: {
                [key: string]: unknown;
            };
        };
        toolFailed: {
            toolCallId: string;
            toolName: string;
            durationMs: number;
            error: components["schemas"]["taskEventError"];
        };
        metricCandidates: {
            candidates: components["schemas"]["candidate"][];
        };
        chartCreated: {
            chart: components["schemas"]["chart"];
        };
        chartExecutionCompleted: {
            chartId: string;
            execution: components["schemas"]["execution"];
            /** @constant */
            chartStatus: "ready";
        };
        taskCompleted: {
            task: components["schemas"]["taskSnapshot"];
        };
        taskFailed: {
            task: components["schemas"]["taskSnapshot"];
            error: components["schemas"]["taskEventError"];
        };
        alertReceived: {
            sourceId: string;
            alertName: string;
            fingerprint: string;
            serviceRef: string;
            /** @enum {string} */
            status: "firing" | "resolved";
            /** Format: date-time */
            startsAt: string;
        };
        playbookResolved: {
            mappingId: string;
            mappingDigest: string;
            playbookId: string;
            playbookVersion: string;
            playbookDigest: string;
        };
        assetsPinned: {
            assets: {
                /** @enum {string} */
                kind: "knowledge" | "skill" | "playbook" | "alert_mapping";
                id: string;
                version: string;
                digest: string;
            }[];
        };
        diagnosisCompleted: {
            /** @enum {string} */
            primaryHypothesis: "worker_stopped" | "slow_processing" | "dependency_errors" | "healthy" | "insufficient_evidence";
            evidenceRefs: string[];
            alternativeHypotheses: string[];
            confidence: number;
            /** @enum {string} */
            candidateAction: "restore_worker_concurrency" | "no_action";
        };
        intentPrepared: {
            intentId: string;
            intentDigest: string;
            /** @constant */
            capabilityId: "order_service.restore_worker_concurrency";
            serviceRef: string;
            instanceEpoch: string;
            expectedVersion: number;
            /** @constant */
            beforeConcurrency: 0;
            /** @constant */
            afterConcurrency: 2;
            /** @constant */
            risk: "low";
        };
        approvalRequested: {
            approvalId: string;
            intentDigest: string;
            /** Format: date-time */
            expiresAt: string;
            version: number;
        };
        approvalDecided: {
            approvalId: string;
            /** @enum {string} */
            status: "approved" | "rejected" | "expired";
            decidedBy: string;
            /** Format: date-time */
            decidedAt: string;
            version: number;
        };
        remediationOperation: {
            operationId: string;
            intentDigest: string;
            /** @enum {string} */
            state: "started" | "applied" | "already_applied" | "failed" | "unknown";
        };
        verification: {
            passed: boolean;
            /** Format: date-time */
            observedAt: string;
            summary: string;
        };
        auditRecorded: {
            auditId: string;
            /** @enum {string} */
            action: "approval_decision" | "remediation_execute" | "remediation_verify";
            /** @enum {string} */
            outcome: "accepted" | "rejected" | "succeeded" | "failed";
        };
        /** TaskEvent */
        "task-events.schema": {
            eventId: string;
            taskId: string;
            sessionId: string;
            sequence: number;
            /** @enum {string} */
            type: "task.created" | "task.status_changed" | "assistant.message.started" | "assistant.message.delta" | "assistant.message.completed" | "tool.started" | "tool.completed" | "tool.failed" | "metric.candidates_created" | "chart.created" | "chart.execution_completed" | "task.completed" | "task.failed" | "alert.received" | "playbook.resolved" | "assets.pinned" | "diagnosis.completed" | "intent.prepared" | "approval.requested" | "approval.decided" | "remediation.started" | "remediation.reconciled" | "verification.runtime" | "verification.metrics" | "verification.business" | "audit.recorded";
            /** Format: date-time */
            timestamp: string;
            payload: Record<string, never>;
            $defs: {
                taskEventError: {
                    code: string;
                    message: string;
                    retryable: boolean;
                    requestId: string;
                } & {
                    [key: string]: unknown;
                };
                taskSnapshot: {
                    id: string;
                    sessionId: string;
                    status: string;
                } & {
                    [key: string]: unknown;
                };
                message: {
                    id: string;
                    sessionId: string;
                    taskId: string;
                    role: string;
                    content: string;
                    /** Format: date-time */
                    createdAt: string;
                } & {
                    [key: string]: unknown;
                };
                candidate: {
                    metricName: string;
                    type: string;
                    description: string;
                    labels: unknown[];
                    score: number;
                    sources: unknown[];
                } & {
                    [key: string]: unknown;
                };
                chart: {
                    id: string;
                    taskId: string;
                    title: string;
                    status: string;
                } & {
                    [key: string]: unknown;
                };
                execution: {
                    id: string;
                    status: string;
                    series: unknown[];
                    seriesCount: number;
                } & {
                    [key: string]: unknown;
                };
                taskCreated: {
                    task: components["schemas"]["taskSnapshot"];
                };
                statusChanged: {
                    /** @enum {string} */
                    previousStatus: "created" | "planning" | "running_tools" | "waiting_approval" | "executing" | "reconciling" | "validating" | "completed" | "failed" | "cancelled";
                    /** @enum {string} */
                    status: "created" | "planning" | "running_tools" | "waiting_approval" | "executing" | "reconciling" | "validating" | "completed" | "failed" | "cancelled";
                    error?: components["schemas"]["taskEventError"];
                };
                assistantStarted: {
                    messageId: string;
                    /** @constant */
                    role: "assistant";
                };
                assistantDelta: {
                    messageId: string;
                    delta: string;
                    ordinal: number;
                };
                assistantCompleted: {
                    message: components["schemas"]["message"];
                };
                toolStarted: {
                    toolCallId: string;
                    toolName: string;
                    /** @constant */
                    toolVersion: "v1";
                    inputSummary: {
                        [key: string]: unknown;
                    };
                };
                toolCompleted: {
                    toolCallId: string;
                    toolName: string;
                    durationMs: number;
                    outputSummary: {
                        [key: string]: unknown;
                    };
                };
                toolFailed: {
                    toolCallId: string;
                    toolName: string;
                    durationMs: number;
                    error: components["schemas"]["taskEventError"];
                };
                metricCandidates: {
                    candidates: components["schemas"]["candidate"][];
                };
                chartCreated: {
                    chart: components["schemas"]["chart"];
                };
                chartExecutionCompleted: {
                    chartId: string;
                    execution: components["schemas"]["execution"];
                    /** @constant */
                    chartStatus: "ready";
                };
                taskCompleted: {
                    task: components["schemas"]["taskSnapshot"];
                };
                taskFailed: {
                    task: components["schemas"]["taskSnapshot"];
                    error: components["schemas"]["taskEventError"];
                };
                alertReceived: {
                    sourceId: string;
                    alertName: string;
                    fingerprint: string;
                    serviceRef: string;
                    /** @enum {string} */
                    status: "firing" | "resolved";
                    /** Format: date-time */
                    startsAt: string;
                };
                playbookResolved: {
                    mappingId: string;
                    mappingDigest: string;
                    playbookId: string;
                    playbookVersion: string;
                    playbookDigest: string;
                };
                assetsPinned: {
                    assets: {
                        /** @enum {string} */
                        kind: "knowledge" | "skill" | "playbook" | "alert_mapping";
                        id: string;
                        version: string;
                        digest: string;
                    }[];
                };
                diagnosisCompleted: {
                    /** @enum {string} */
                    primaryHypothesis: "worker_stopped" | "slow_processing" | "dependency_errors" | "healthy" | "insufficient_evidence";
                    evidenceRefs: string[];
                    alternativeHypotheses: string[];
                    confidence: number;
                    /** @enum {string} */
                    candidateAction: "restore_worker_concurrency" | "no_action";
                };
                intentPrepared: {
                    intentId: string;
                    intentDigest: string;
                    /** @constant */
                    capabilityId: "order_service.restore_worker_concurrency";
                    serviceRef: string;
                    instanceEpoch: string;
                    expectedVersion: number;
                    /** @constant */
                    beforeConcurrency: 0;
                    /** @constant */
                    afterConcurrency: 2;
                    /** @constant */
                    risk: "low";
                };
                approvalRequested: {
                    approvalId: string;
                    intentDigest: string;
                    /** Format: date-time */
                    expiresAt: string;
                    version: number;
                };
                approvalDecided: {
                    approvalId: string;
                    /** @enum {string} */
                    status: "approved" | "rejected" | "expired";
                    decidedBy: string;
                    /** Format: date-time */
                    decidedAt: string;
                    version: number;
                };
                remediationOperation: {
                    operationId: string;
                    intentDigest: string;
                    /** @enum {string} */
                    state: "started" | "applied" | "already_applied" | "failed" | "unknown";
                };
                verification: {
                    passed: boolean;
                    /** Format: date-time */
                    observedAt: string;
                    summary: string;
                };
                auditRecorded: {
                    auditId: string;
                    /** @enum {string} */
                    action: "approval_decision" | "remediation_execute" | "remediation_verify";
                    /** @enum {string} */
                    outcome: "accepted" | "rejected" | "succeeded" | "failed";
                };
            };
        } & ({
            /** @constant */
            type?: "task.created";
            payload?: components["schemas"]["taskCreated"];
        } | {
            /** @constant */
            type?: "task.status_changed";
            payload?: components["schemas"]["statusChanged"];
        } | {
            /** @constant */
            type?: "assistant.message.started";
            payload?: components["schemas"]["assistantStarted"];
        } | {
            /** @constant */
            type?: "assistant.message.delta";
            payload?: components["schemas"]["assistantDelta"];
        } | {
            /** @constant */
            type?: "assistant.message.completed";
            payload?: components["schemas"]["assistantCompleted"];
        } | {
            /** @constant */
            type?: "tool.started";
            payload?: components["schemas"]["toolStarted"];
        } | {
            /** @constant */
            type?: "tool.completed";
            payload?: components["schemas"]["toolCompleted"];
        } | {
            /** @constant */
            type?: "tool.failed";
            payload?: components["schemas"]["toolFailed"];
        } | {
            /** @constant */
            type?: "metric.candidates_created";
            payload?: components["schemas"]["metricCandidates"];
        } | {
            /** @constant */
            type?: "chart.created";
            payload?: components["schemas"]["chartCreated"];
        } | {
            /** @constant */
            type?: "chart.execution_completed";
            payload?: components["schemas"]["chartExecutionCompleted"];
        } | {
            /** @constant */
            type?: "task.completed";
            payload?: components["schemas"]["taskCompleted"];
        } | {
            /** @constant */
            type?: "task.failed";
            payload?: components["schemas"]["taskFailed"];
        } | {
            /** @constant */
            type?: "alert.received";
            payload?: components["schemas"]["alertReceived"];
        } | {
            /** @constant */
            type?: "playbook.resolved";
            payload?: components["schemas"]["playbookResolved"];
        } | {
            /** @constant */
            type?: "assets.pinned";
            payload?: components["schemas"]["assetsPinned"];
        } | {
            /** @constant */
            type?: "diagnosis.completed";
            payload?: components["schemas"]["diagnosisCompleted"];
        } | {
            /** @constant */
            type?: "intent.prepared";
            payload?: components["schemas"]["intentPrepared"];
        } | {
            /** @constant */
            type?: "approval.requested";
            payload?: components["schemas"]["approvalRequested"];
        } | {
            /** @constant */
            type?: "approval.decided";
            payload?: components["schemas"]["approvalDecided"];
        } | {
            /** @constant */
            type?: "remediation.started";
            payload?: components["schemas"]["remediationOperation"];
        } | {
            /** @constant */
            type?: "remediation.reconciled";
            payload?: components["schemas"]["remediationOperation"];
        } | {
            /** @constant */
            type?: "verification.runtime";
            payload?: components["schemas"]["verification"];
        } | {
            /** @constant */
            type?: "verification.metrics";
            payload?: components["schemas"]["verification"];
        } | {
            /** @constant */
            type?: "verification.business";
            payload?: components["schemas"]["verification"];
        } | {
            /** @constant */
            type?: "audit.recorded";
            payload?: components["schemas"]["auditRecorded"];
        });
        /** TaskEventReplayPage */
        "task-event-replay-page.schema": {
            items: components["schemas"]["task-events.schema"][];
            targetSequence: number;
            nextPageToken: string | null;
        };
        query: {
            refId: string;
            expression: string;
            legend: string;
            /** @enum {string} */
            datasourceUid: "prometheus-main";
            timeRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @enum {integer} */
            stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
        };
        /** ChartDraft */
        "chart.schema": {
            id: string;
            sessionId: string;
            taskId: string;
            title: string;
            /** @constant */
            visualization: "timeseries";
            unit: string;
            queries: components["schemas"]["query"][];
            /** @enum {string} */
            status: "proposed" | "ready";
            latestExecutionId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            version: number;
            $defs: {
                query: {
                    refId: string;
                    expression: string;
                    legend: string;
                    /** @enum {string} */
                    datasourceUid: "prometheus-main";
                    timeRange: {
                        /** Format: date-time */
                        from: string;
                        /** Format: date-time */
                        to: string;
                    };
                    /** @enum {integer} */
                    stepSeconds: 5 | 10 | 15 | 30 | 60 | 120 | 300;
                };
            };
        };
        /** ChartExecution */
        "execution.schema": {
            id: string;
            queryRefId: string;
            /** @enum {string} */
            status: "success" | "failed";
            seriesCount: number;
            durationMs: number;
            sampleRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            actualSampleRange: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            } | null;
            series: {
                name: string;
                labels: {
                    [key: string]: string;
                };
                points: {
                    /** Format: date-time */
                    timestamp: string;
                    value: number;
                }[];
            }[];
            warnings: string[];
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Structured domain error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["error.schema"];
            };
        };
    };
    parameters: {
        SessionId: string;
        TaskId: string;
        IdempotencyKey: string;
        RequestId: string;
        TraceId: string;
        TraceParent: string;
        AfterSequence: number;
        PageSizeMessages: number;
        PageSizeTasks: number;
        PageSizeSessions: number;
        PageSizeReplay: number;
        PageToken: string;
        LastEventId: number;
        TenantId: string;
        OrgId: string;
        UserId: string;
        /** @description Comma-separated, trimmed and de-duplicated roles. */
        Roles: string;
        /** @description Comma-separated permissions; must include datasources:query for this profile. */
        Permissions: string;
        AlertSource: string;
        /** @description Unix timestamp accepted only within the configured replay window. */
        AlertTimestamp: number;
        AlertSignature: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingestGrafanaAlert: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Alert-Source": components["parameters"]["AlertSource"];
                /** @description Unix timestamp accepted only within the configured replay window. */
                "X-MTB-Alert-Timestamp": components["parameters"]["AlertTimestamp"];
                "X-Grafana-Alerting-Signature": components["parameters"]["AlertSignature"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["grafana-alert-webhook.schema"];
            };
        };
        responses: {
            /** @description Firing alerts accepted or deduplicated */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["alert-ingress-response.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Migrations, storage and MCP dependency are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ErrorResponse"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeSessions"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped Session page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["session-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["create-session-request.schema"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["session.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["session.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSessionMessages: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeMessages"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["message-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSessionTasks: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeTasks"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["create-task-request.schema"];
            };
        };
        responses: {
            /** @description Task accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listIncidents: {
        parameters: {
            query?: {
                pageSize?: components["parameters"]["PageSizeTasks"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization-scoped Incident Task page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getTaskApproval: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["approval.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    decideTaskApproval: {
        parameters: {
            query?: never;
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["decide-approval-request.schema"];
            };
        };
        responses: {
            /** @description Decision persisted and workflow scheduled */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["approval.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: {
                afterSequence?: components["parameters"]["AfterSequence"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "Last-Event-ID"?: components["parameters"]["LastEventId"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable TaskEvent stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["task-events.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    replayTaskEvents: {
        parameters: {
            query?: {
                afterSequence?: components["parameters"]["AfterSequence"];
                pageSize?: components["parameters"]["PageSizeReplay"];
                pageToken?: components["parameters"]["PageToken"];
            };
            header: {
                "X-MTB-Tenant-ID": components["parameters"]["TenantId"];
                "X-MTB-Org-ID": components["parameters"]["OrgId"];
                "X-MTB-User-ID": components["parameters"]["UserId"];
                /** @description Comma-separated, trimmed and de-duplicated roles. */
                "X-MTB-Roles": components["parameters"]["Roles"];
                /** @description Comma-separated permissions; must include datasources:query for this profile. */
                "X-MTB-Permissions": components["parameters"]["Permissions"];
                "X-Request-ID": components["parameters"]["RequestId"];
                "X-Trace-ID": components["parameters"]["TraceId"];
                traceparent?: components["parameters"]["TraceParent"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finite replay page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["task-event-replay-page.schema"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
